In [4]:
import pandas as pd

# Load the CSV file
df = pd.read_csv('giftcart_cleaned_final_proper.csv')

# Select only Handle, Title, and Description columns
df_filtered = df[['Handle', 'Title', 'Description']].copy()

# Remove rows where all three columns are empty/null
df_filtered = df_filtered.dropna(how='all')

# Also remove rows where all three are empty strings
df_filtered = df_filtered[~((df_filtered['Handle'].fillna('').str.strip() == '') & 
                             (df_filtered['Title'].fillna('').str.strip() == '') & 
                             (df_filtered['Description'].fillna('').str.strip() == ''))]

print(f"Total rows extracted: {len(df_filtered)}")
df_filtered.head(10)

Total rows extracted: 6082

,Handle,Title,Description
0,harsheys-chocolate,You Make My Heart Smila Hamper of Love,Make this Valentine’s Day unforgettable for yo...
1,personalised-mdf-sqaure-puzzle,Personalised MDF Sqaure Puzzle,Transform your favorite photo into a fun puzzl...
2,celebration-gift-box-cashews-almonds-raisins-1...,"Celebration Gift Box (Cashews, Almonds , Raisi...",Nutslane Premium Celebration Gift Box | Plain ...
3,mia-gift-box-rose-almond-anardana-raisins-roas...,"Mia Gift Box( Rose Almond, Anardana raisins , ...",Premium Mia Gift Box | Mexican Salsa Cashews |...
4,roohani-mexican-salsa-cashews-rose-almonds-bbq...,"Roohani (Mexican Salsa Cashews , Rose Almonds ...",The Roohani Gift Box is a premium collection o...
5,aayat-cream-onion-peri-peri-indian-mint-mkahan...,"Aayat (Cream Onion , Peri peri , Indian Mint M...",Enjoy a flavorful journey with the Nutslane Aa...
6,roohi-bbq-almond-180-gram-paan-raisins-200-gra...,"Roohi (BBQ Almond - 180 Gram , Paan Raisins - ...",Shahi Paan Raisin (200g) Royal raisins infused...
7,sanjh-rose-almond-80-gram-peri-peri-makhana-50...,"Sanjh (Rose Almond - 80 Gram, Peri Peri makhan...",Saanj Gift Box | Curated Gourmet Delights | In...
8,noor-gift-box-rose-almond-180-gram-pan-raisins...,Noor Gift Box (Rose Almond - 180 Gram & Pan Ra...,Noor Gift Box | Luxurious Fusion of Flavors | ...
9,rugby-stress-ball,Rugby Stress Ball,Tackle your stress with this fun rugby-shaped ...

In [5]:
# Add auto-incrementing ID column
df_filtered.insert(0, 'id', range(1, len(df_filtered) + 1))

# Save to CSV file
df_filtered.to_csv('giftcart_cleaned_products_6000.csv', index=False)

print(f"Saved {len(df_filtered)} rows to giftcart_cleaned_products_6000.csv")
df_filtered.head(10)

Saved 6082 rows to giftcart_cleaned_products_6000.csv

,id,Handle,Title,Description
0,1,harsheys-chocolate,You Make My Heart Smila Hamper of Love,Make this Valentine’s Day unforgettable for yo...
1,2,personalised-mdf-sqaure-puzzle,Personalised MDF Sqaure Puzzle,Transform your favorite photo into a fun puzzl...
2,3,celebration-gift-box-cashews-almonds-raisins-1...,"Celebration Gift Box (Cashews, Almonds , Raisi...",Nutslane Premium Celebration Gift Box | Plain ...
3,4,mia-gift-box-rose-almond-anardana-raisins-roas...,"Mia Gift Box( Rose Almond, Anardana raisins , ...",Premium Mia Gift Box | Mexican Salsa Cashews |...
4,5,roohani-mexican-salsa-cashews-rose-almonds-bbq...,"Roohani (Mexican Salsa Cashews , Rose Almonds ...",The Roohani Gift Box is a premium collection o...
5,6,aayat-cream-onion-peri-peri-indian-mint-mkahan...,"Aayat (Cream Onion , Peri peri , Indian Mint M...",Enjoy a flavorful journey with the Nutslane Aa...
6,7,roohi-bbq-almond-180-gram-paan-raisins-200-gra...,"Roohi (BBQ Almond - 180 Gram , Paan Raisins - ...",Shahi Paan Raisin (200g) Royal raisins infused...
7,8,sanjh-rose-almond-80-gram-peri-peri-makhana-50...,"Sanjh (Rose Almond - 80 Gram, Peri Peri makhan...",Saanj Gift Box | Curated Gourmet Delights | In...
8,9,noor-gift-box-rose-almond-180-gram-pan-raisins...,Noor Gift Box (Rose Almond - 180 Gram & Pan Ra...,Noor Gift Box | Luxurious Fusion of Flavors | ...
9,10,rugby-stress-ball,Rugby Stress Ball,Tackle your stress with this fun rugby-shaped ...